GROUP=io.github.suppierk
VERSION_NAME=2026.07.28.1.0-SNAPSHOT
MCP_REVISION=2026-07-28

POM_NAME=MCP Server Kit for Java
POM_DESCRIPTION=A framework-independent Java library for implementing MCP servers
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/SuppieRK/mcp-server-kit-java

POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://github.com/SuppieRK/mcp-server-kit-java/blob/main/LICENSE
POM_LICENCE_DIST=repo

POM_SCM_URL=https://github.com/SuppieRK/mcp-server-kit-java
POM_SCM_CONNECTION=scm:git:git://github.com/SuppieRK/mcp-server-kit-java.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/SuppieRK/mcp-server-kit-java.git

POM_DEVELOPER_ID=SuppieRK
POM_DEVELOPER_NAME=Roman Khlebnov
POM_DEVELOPER_URL=https://github.com/SuppieRK/

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=true
SONATYPE_CONNECT_TIMEOUT_SECONDS=300
SONATYPE_CLOSE_TIMEOUT_SECONDS=1800

org.gradle.caching=true
org.gradle.parallel=true
systemProp.sonar.gradle.skipCompile=true
